### ISSUE TITLE
No module named 'biupsample_naive_cuda'

### ISSUE THREAD

**Issue by antithing** [dongdong93/a2u_matting#1]
Hi, and thank you for making this code available!  i am trying to run it on windows, and i see this error when running demo.py:

Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    from resnet import resnetmat
  File "D:\Deep\a2u_matting\a2u_matting-main\scripts\resnet.py", line 16, in <module>
    from decoder import *
  File "D:\Deep\a2u_matting\a2u_matting-main\scripts\decoder.py", line 6, in <module>
    from BilinearModel import InterChannelOperation
  File "D:\Deep\a2u_matting\a2u_matting-main\scripts\BilinearModel.py", line 6, in <module>
    from Biupdownsample import bidownsample_naive, biupsample_naive
  File "D:\Deep\a2u_matting\a2u_matting-main\scripts\Biupdownsample\__init__.py", line 1, in <module>
    from .biupdownsample import BiupsampleNaive, biupsample_naive, BidownsampleNaive, bidownsample_naive
  File "D:\Deep\a2u_matting\a2u_matting-main\scripts\Biupdownsample\biupdownsample.py", line 7, in <module>
    import biupsample_naive_cuda, bidownsample_naive_cuda
ModuleNotFoundError: No module named 'biupsample_naive_cuda'

Am I missing a dependency?

Thank you!

**Comment by poppinace** [comment]
hi, have you compiled the code before running demo?
